snapshot

diff --git a/texc b/texc
--- a/texc
+++ b/texc
@@ -1,4 +1,9 @@
-#/bin/sh!
+#/bin/bash!
+texc_cleanup () {
+  echo "\033[34;1;4m> Cleanup ...\033[m"
+  rm -f tmp_texc.* tmp.texc.*
+}
+trap 'texc_cleanup' 2
 (
   that=$(curl -s https://raw.githubusercontent.com/gw31415/texc/master/texc | sha256sum)
   this=$(cat $0 | sha256sum)
@@ -22,6 +27,10 @@ if [ $# -eq 1 ]; then
   save=$file
 elif [ $# -eq 2 ] && [ $1 = '-l' ]; then
   echo "\033[32m> mode:[latexmk]\033[m"
+  if [ ! -e $2 ]; then
+    echo "\033[31;1m> ERROR: \"$2\" does not exist.\033[m"
+    exit
+  fi
   echo "{ \"main\": \"$2\" }" > tmp.texc.json
   echo "\033[34;1;4m> Packing ...\033[m\033[33m"
   tar -cvf tmp_texc.tar *
@@ -51,6 +60,5 @@ fi
 echo "\033[34;1;4m> Downloading ...\033[m"
 curl -so ${name%.*}.pdf $url
 echo "  \033[32mFile saved: ${name%.*}.pdf\033[m"
-echo "\033[34;1;4m> Cleanup ...\033[m"
-rm -f tmp_texc.* tmp.texc.*
+texc_cleanup
 echo "\033[34;1;4m> Done!\033[m"
